### ISSUE TITLE
How can I access to private key of the account?

### ISSUE THREAD

**Issue by scalalang2** [kinfoundation/kin-sdk-core-stellar-ios#4]
Hi. guys.

How can I get a private key of the account?
Is there any available function for it?

Either do this sdk already keep user's private key on keystore?

Thanks.

**Comment by avi-kik** [comment]
At this time, there is no way to export the private keys.  However, the data to generate the keys is stored in the keychain, so you can implement the functions yourself.

I am sorry I can't provide more direct assistance, but the company's current policy is to avoid exposing such functionality.
